import PAGE_LOAD_HELPER_TYPES from './constants';

const VENUES_CONFIG = [
  {
    venue: 'The Garage',
    eventUrls: ['https://www.thegarage.london/live/'],
    eventCardSelector: '.card--full',
    eventCardArtistSelector: '.card__heading',
    eventCardDateSelector: 'h6',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '.button__close',
  },
  {
    venue: 'Scala',
    eventUrls: ['https://scala.co.uk/events/categories/live-music/'],
    eventCardSelector: '.tb-event-item',
    eventCardArtistSelector: 'h2',
    eventCardDateSelector: '.date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'KOKO',
    eventUrls: ['https://www.koko.co.uk/whats-on'],
    eventCardSelector: '[class*=Event_component]',
    eventCardArtistSelector: '[class*=Event_title]',
    eventCardDateSelector: '[class*=Event_date]',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Electric Ballroom',
    eventUrls: ['https://electricballroom.co.uk/whats-on/'],
    eventCardSelector: '.card',
    eventCardArtistSelector: 'h2',
    eventCardDateSelector: '.event-date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Roundhouse',
    eventUrls: ['https://www.roundhouse.org.uk/whats-on/?type=event'],
    eventCardSelector: '.event-card',
    eventCardArtistSelector: '.event-card__title',
    eventCardDateSelector: '.event-card__details',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.button--loadmore',
    cookiePolicyModalAcceptButtonSelector: '.cookie-policy__popup .button--primary',
    pageLoadHelper: {
      type: PAGE_LOAD_HELPER_TYPES.REMOVE_ELEMENT,
      options: {
        selector: '.filters-bar',
      },
    },
  },
  {
    venue: 'Eventim Apollo',
    eventUrls: ['https://www.eventimapollo.com/events',
      'https://www.eventimapollo.com/events/m/1/#month-filters',
      'https://www.eventimapollo.com/events/m/2/#month-filters',
      'https://www.eventimapollo.com/events/m/3/#month-filters',
      'https://www.eventimapollo.com/events/m/4/#month-filters',
      'https://www.eventimapollo.com/events/m/5/#month-filters',
      'https://www.eventimapollo.com/events/m/6/#month-filters',
      'https://www.eventimapollo.com/events/m/7/#month-filters',
      'https://www.eventimapollo.com/events/m/8/#month-filters',
      'https://www.eventimapollo.com/events/m/9/#month-filters',
      'https://www.eventimapollo.com/events/m/10/#month-filters',
    ],
    eventCardSelector: '.card',
    eventCardArtistSelector: 'h3',
    eventCardDateSelector: '.date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.event-index__load-more',
    cookiePolicyModalAcceptButtonSelector: '#onetrust-accept-btn-handler',
  },
  {
    venue: 'Alexandra Palace',
    eventUrls: ['https://www.alexandrapalace.com/whats-on/'],
    eventCardSelector: '[class*=whats-on-item]:not(.past-event)',
    eventCardArtistSelector: 'h3',
    eventCardDateSelector: '.dates',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Omeara',
    eventUrls: ['https://omearalondon.com/events/?event-type=live&currentpage=1'],
    eventCardSelector: '.events-grid-view__event-card',
    eventCardArtistSelector: '.event-title',
    eventCardDateSelector: '.event-date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '.cky-btn-accept',
  },
  {
    venue: 'EartH',
    eventUrls: ['https://earthackney.co.uk/events/'],
    eventCardSelector: '.list--events__item',
    eventCardArtistSelector: '.list--events__item__title',
    eventCardDateSelector: '.list--events__item__dates > time:nth-child(1)',
    eventCardDescriptionSelector: '.list--events__item__description',
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Village Underground',
    eventUrls: ['https://villageunderground.co.uk/events/'],
    eventCardSelector: '.list--events__item',
    eventCardArtistSelector: '.list--events__item__title',
    eventCardDateSelector: '.list--events__item__dates > time:nth-child(1)',
    eventCardDescriptionSelector: '.list--events__item__description',
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The O2',
    eventUrls: ['https://www.theo2.co.uk/events/venue/the-o2-arena'],
    eventCardSelector: '.eventItem',
    eventCardArtistSelector: 'h3',
    eventCardDateSelector: '.date.divider-date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '#loadMoreEvents',
    cookiePolicyModalAcceptButtonSelector: '#onetrust-button-group #onetrust-accept-btn-handler',
  },
  {
    venue: 'barbican',
    eventUrls: ['https://www.barbican.org.uk/whats-on/contemporary-music'],
    eventCardSelector: 'article.listing--event',
    eventCardArtistSelector: '.listing-title--event',
    eventCardDateSelector: '.listing-date',
    eventCardDescriptionSelector: '.search-listing__intro div:nth-child(2)',
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '.cookie-notice .cm-btn-success',
  },
  {
    venue: 'Troxy',
    eventUrls: ['https://troxy.co.uk/whats-on/'],
    eventCardSelector: '.events-col',
    eventCardArtistSelector: 'h3',
    eventCardDateSelector: '.date-and-title',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'HERE at Outernet',
    eventUrls: ['https://dice.fm/venue/here-at-outernet-wgbx'],
    eventCardSelector: '[class*=EventParts__EventBlock]',
    eventCardArtistSelector: '[class*=EventParts__EventName]',
    eventCardDateSelector: '[class*=EventParts__EventDate]',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '[class*=idOrSlug__MoreButton]',
    cookiePolicyModalAcceptButtonSelector: '.ch2-dialog-actions .ch2-btn-primary',
  },
  {
    venue: 'The Lower Third',
    eventUrls: ['https://dice.fm/venue/the-lower-third-pply'],
    eventCardSelector: '[class*=EventParts__EventBlock]',
    eventCardArtistSelector: '[class*=EventParts__EventName]',
    eventCardDateSelector: '[class*=EventParts__EventDate]',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '[class*=idOrSlug__MoreButton]',
    cookiePolicyModalAcceptButtonSelector: '.ch2-dialog-actions .ch2-btn-primary',
  },
  {
    venue: 'Islington Assembly Hall',
    eventUrls: ['https://islingtonassemblyhall.co.uk/events/'],
    eventCardSelector: '.event__item',
    eventCardArtistSelector: '.event__item__title',
    eventCardDateSelector: '.event__item__date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The Dome',
    eventUrls: ['https://domelondon.co.uk/all-events'],
    eventCardSelector: 'article[class*=eventlist-event]:not(.eventlist-event--past)',
    eventCardArtistSelector: 'h1.eventlist-title',
    eventCardDateSelector: 'time.event-date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '.sqs-cookie-banner-v2-accept',
  },
  {
    venue: 'Wembley Stadium',
    eventUrls: ['https://www.wembleystadium.com/events'],
    eventCardSelector: '.fa-filter-content__item',
    eventCardArtistSelector: 'h2',
    eventCardDateSelector: '.fa-content-promo__content span.small-text',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '#onetrust-accept-btn-handler',
  },
  {
    venue: 'Ovo Arena',
    eventUrls: ['https://www.ovoarena.co.uk/events'],
    eventCardSelector: '.eventItemWrapperEvent',
    eventCardArtistSelector: '.title',
    eventCardDateSelector: '.date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '#loadMoreEvents',
    cookiePolicyModalAcceptButtonSelector: '.cc-compliance .cc-allow',
  },
  {
    venue: 'South Bank Centre',
    eventUrls: ['https://www.southbankcentre.co.uk/whats-on?type=gigs'],
    eventCardSelector: '.arrangement-card__container',
    eventCardArtistSelector: '.arrangement-card__title',
    eventCardDateSelector: '.arrangement-card__date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
    pageLoadHelper: {
      type: PAGE_LOAD_HELPER_TYPES.CLICK_ELEMENT,
      options: {
        selector: '.newsletter-modal__close',
      },
    },
  },
  {
    venue: 'Union Chapel',
    eventUrls: ['https://unionchapel.org.uk/whats-on'],
    eventCardSelector: '.card',
    eventCardArtistSelector: '.card-inner > p.card-title',
    eventCardDateSelector: '.card-inner > p > strong',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '#cookiescript_accept',
  },
  {
    venue: 'Dingwalls',
    eventUrls: ['https://powerhauscamden.com/whats-on/'],
    eventCardSelector: 'section.page__content > div',
    eventCardArtistSelector: '.feed__title',
    eventCardDateSelector: 'p',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '#ccc-notify-accept',
  },
  {
    venue: 'The Underworld',
    eventUrls: ['https://www.theunderworldcamden.co.uk/'],
    eventCardSelector: '#gigs article',
    eventCardArtistSelector: '.list-header-title',
    eventCardDateSelector: '.list-header-date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Bush Hall',
    eventUrls: ['https://bushhallmusic.co.uk/pages/whats-on'],
    eventCardSelector: '.dice-widget article',
    eventCardArtistSelector: '.dice_event-title',
    eventCardDateSelector: 'time',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'MOTH Club',
    eventUrls: ['https://mothclub.co.uk/events'],
    eventCardSelector: '.dice-widget article',
    eventCardArtistSelector: '.dice_event-title',
    eventCardDateSelector: 'time',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.dice_load-more',
    cookiePolicyModalAcceptButtonSelector: '.mc-closeModal',
  },
  {
    venue: 'The Camden Assembly',
    eventUrls: ['https://www.camdenassembly.com/live-shows/'],
    eventCardSelector: '.upcommingevents .elementor-posts article',
    eventCardArtistSelector: '.elementor-post__title',
    eventCardDateSelector: '.elementor-post__excerpt',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'OSLO',
    eventUrls: ['https://www.oslohackney.com/events/'],
    eventCardSelector: '.card--full',
    eventCardArtistSelector: '.card__heading',
    eventCardDateSelector: 'h6',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Colours',
    eventUrls: ['https://colourshoxton.com/live-club/'],
    eventCardSelector: 'div.tw-section',
    eventCardArtistSelector: '.tw-name',
    eventCardDateSelector: '.tw-date-time',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: 'span.next a',
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The Shacklewell Arms',
    eventUrls: ['https://www.shacklewellarms.com/events'],
    eventCardSelector: '.dice_events article',
    eventCardArtistSelector: '.dice_event-title',
    eventCardDateSelector: 'time',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.dice_load-more',
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Notting Hill Arts Club',
    eventUrls: [
      'https://nottinghillartsclub.com/events-list/?filter[month]=2023-10',
      'https://nottinghillartsclub.com/events-list/?filter[month]=2023-11',
      'https://nottinghillartsclub.com/events-list/?filter[month]=2023-12',
      'https://nottinghillartsclub.com/events-list/?filter[month]=2024-01',
      'https://nottinghillartsclub.com/events-list/?filter[month]=2024-02',
      'https://nottinghillartsclub.com/events-list/?filter[month]=2024-03',
      'https://nottinghillartsclub.com/events-list/?filter[month]=2024-04',
      'https://nottinghillartsclub.com/events-list/?filter[month]=2024-05',
    ],
    eventCardSelector: '.event',
    eventCardArtistSelector: '.title',
    eventCardDateSelector: '.eventlist-datetag-startdate',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Paper Dress Vintage',
    eventUrls: ['https://paperdressvintage.co.uk/by-night'],
    eventCardSelector: '.events__event',
    eventCardArtistSelector: 'h4',
    eventCardDateSelector: 'p',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The Old Blue Last',
    eventUrls: ['https://www.theoldbluelast.com/'],
    eventCardSelector: '.dice-widget article',
    eventCardArtistSelector: '.dice_event-title',
    eventCardDateSelector: 'time',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.dice_load-more',
    cookiePolicyModalAcceptButtonSelector: undefined,
    pageLoadHelper: {
      type: PAGE_LOAD_HELPER_TYPES.CLICK_ELEMENT,
      options: {
        selector: '.sqs-popup-overlay-close',
      },
    },
  },
  {
    venue: 'The Grace',
    eventUrls: ['https://www.thegrace.london/whats-on/'],
    eventCardSelector: '.card--full',
    eventCardArtistSelector: '.card__heading',
    eventCardDateSelector: 'h6',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The Waiting Room',
    eventUrls: ['https://www.thewaitingroomn16.com/'],
    eventCardSelector: '.grid-item',
    eventCardArtistSelector: '.event_title',
    eventCardDateSelector: '.date_time',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The 100 Club',
    eventUrls: ['https://www.the100club.co.uk/events-calendar/'],
    eventCardSelector: 'div.fc-event-list-content',
    eventCardArtistSelector: 'h4',
    eventCardDateSelector: '.fc-event-list-description h5',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Lafayette',
    eventUrls: ['https://www.lafayettelondon.com/'],
    eventCardSelector: 'div.event_listings .polaroid_blocks li',
    eventCardArtistSelector: 'h1',
    eventCardDateSelector: '.date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'Electric Brixton',
    eventUrls: ['https://www.electricbrixton.uk.com/events/'],
    eventCardSelector: '#whats-on-events .fl-post-column',
    eventCardArtistSelector: 'h3.event-title',
    eventCardDateSelector: 'h4.event-date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.fl-builder-pagination-load-more a',
    cookiePolicyModalAcceptButtonSelector: '#wt-cli-accept-all-btn',
  },
  {
    venue: 'The Black Heart',
    eventUrls: ['https://www.ourblackheart.com/events'],
    eventCardSelector: 'article.eventlist-event',
    eventCardArtistSelector: 'h1',
    eventCardDateSelector: '.eventlist-datetag-inner',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The Sebright Arms',
    eventUrls: ['https://www.sebrightarms.com/'],
    eventCardSelector: '#dice-event-list-widget article',
    eventCardArtistSelector: '.dice_event-title',
    eventCardDateSelector: 'time',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.dice_load-more',
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The Social',
    eventUrls: ['https://www.thesocial.com/events/'],
    eventCardSelector: '#evcal_list .desc_trig_outter',
    eventCardArtistSelector: 'span.evcal_event_title',
    eventCardDateSelector: '.evo_start',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '#evcal_next',
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'The Jazz Cafe',
    eventUrls: ['https://thejazzcafelondon.com/whats-on/'],
    eventCardSelector: '#events-list .event',
    eventCardArtistSelector: 'h2.event-title',
    eventCardDateSelector: '.event-date',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: undefined,
    cookiePolicyModalAcceptButtonSelector: '.overlay-buttons #js-gdpr-accept',
  },
  {
    venue: 'Royal Albert Hall',
    eventUrls: ['https://www.royalalberthall.com/tickets/'],
    eventCardSelector: '.area-production-list article',
    eventCardArtistSelector: 'h3.title',
    eventCardDateSelector: '.date-description',
    eventCardDescriptionSelector: undefined,
    loadMoreButtonSelector: '.unit-pagination-loader a',
    cookiePolicyModalAcceptButtonSelector: 'button#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
    pageLoadHelper: {
      type: PAGE_LOAD_HELPER_TYPES.MANUAL_INTERACTION,
    },
  },
  {
    venue: "O2 Empire Shepherd's Bush",
    eventUrls: ['https://www.academymusicgroup.com/o2shepherdsbushempire/events/all'],
    eventCardSelector: 'div.item-list li',
    alternateProcessingConfig: {
      newTabLinkSelector: '.event-actions a',
    },
    eventCardArtistSelector: '.event-details h1',
    eventCardDateSelector: '.event-info p',
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'O2 Forum Kentish Town',
    eventUrls: ['https://www.academymusicgroup.com/o2forumkentishtown/events/all'],
    eventCardSelector: 'div.item-list li',
    alternateProcessingConfig: {
      newTabLinkSelector: '.event-actions a',
    },
    eventCardArtistSelector: '.event-details h1',
    eventCardDateSelector: '.event-info p',
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
  {
    venue: 'O2 Academy Islington',
    eventUrls: ['https://www.academymusicgroup.com/o2academyislington/events/all'],
    eventCardSelector: 'div.item-list li',
    alternateProcessingConfig: {
      newTabLinkSelector: '.event-actions a',
    },
    eventCardArtistSelector: '.event-details h1',
    eventCardDateSelector: '.event-info p',
    cookiePolicyModalAcceptButtonSelector: undefined,
  },
];

export default VENUES_CONFIG;
